# Generated by Django 3.2.8 on 2021-11-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0002_leilao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('comprador', models.CharField(max_length=200)),
                ('leilao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('efetuador', models.CharField(max_length=200)),
                ('taxaDeComissao', models.FloatField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipoFinal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='tipoInicial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='valorMinimo',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='valorMinimoLance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='lote',
            name='valorReserva',
            field=models.FloatField(),
        ),
    ]
