# Generated by Django 3.2.8 on 2021-11-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0003_auto_20211111_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lance',
            name='leilao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='maiorLance',
            field=models.FloatField(),
        ),
    ]
