# Generated by Django 3.2.8 on 2021-11-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0004_auto_20211111_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='valorMinimoLance',
            field=models.FloatField(null=True),
        ),
    ]
