# Generated by Django 3.2.8 on 2021-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0006_auto_20211111_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leilao',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='lote',
            field=models.IntegerField(default=None),
        ),
    ]
