# Generated by Django 3.2.8 on 2021-11-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0008_alter_pagamento_taxadecomissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='taxaDeComissao',
            field=models.FloatField(null=True),
        ),
    ]
