# Generated by Django 3.2.8 on 2021-11-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0010_remove_pagamento_taxadecomissao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='lote',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
