# Generated by Django 3.2.8 on 2021-11-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0012_auto_20211112_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leilao',
            name='vencedor',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
