# Generated by Django 3.2.8 on 2021-11-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0015_auto_20211118_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='pendente',
            field=models.BooleanField(default=False),
        ),
    ]
