# Generated by Django 3.2.9 on 2021-11-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0017_alter_lote_valorminimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='dataDeConfirmacao',
            field=models.DateField(null=True),
        ),
    ]
