# Generated by Django 3.2.8 on 2021-11-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lote', '0018_pagamento_datadeconfirmacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
